[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = ""
client_id = ""
client_secret = ""
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"


[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = ""
app_password = ""
